### ISSUE TITLE
Documentation on boost/discard numerical importance

### ISSUE THREAD

**Issue by dpbriggs** [brave/goggles-quickstart#16] opened 2022-08-16 19:02 UTC
My apologies if I've missed it in the docs, but does ranking something with a higher number give it more importance? It's not clear how `$boost=3` interacts with `$boost=1`? Will `$boost=3` items show up above `$boost=1` items?

**Comment by devidw** [comment] 2022-08-17 06:04
Furthermore, in this context, it would be interesting to know if a `$boost` without an explicit defined strength is equal to `$boost=1` or `$boost=2`?

[Here](https://search.brave.com/goggles/discover?goggles_id=https%3A%2F%2Fraw.githubusercontent.com%2Fbrave%2Fgoggles-quickstart%2Fmain%2Fgoggles%2Frust_programming.goggle&nav=site) it says it's `2`, is this correct?

![Screenshot 2022-08-17 at 08 00 39](https://user-images.githubusercontent.com/68775926/185046059-c78bc408-b245-472c-9c3e-c8cb756fb2dc.png)

**Comment by Ompanime** [comment] 2022-08-17 17:47
> My apologies if I've missed it in the docs, but does ranking something with a higher number give it more importance? It's not > clear how `$boost=3` interacts with `$boost=1`? Will `$boost=3` items show up above `$boost=1` items?

Hey @dpbriggs, the short answer is yes! In section 5 (Language for _Goggles_) of the whitepaper it reads: 

> We leverage this syntax to add ways to further fine-tune the behaviour of _Goggles_;
> either to specify which features of a result candidate should be considered
> (i.e. _target_), or how the ranking should be affected (i.e. _action_).
> For example:
> **• $boost=XX**—is used to alter the ranking of specific results
> by XX (e.g. _$boost=1_ would not alter the ranking, while
> _$boost=2_ would make a result two times more important).

If you'd like to see this for yourself, the whitepaper is here: [https://brave.com/static-assets/files/goggles.pdf](url)
Hope this helps!

**Comment by Ompanime** [comment] 2022-08-17 18:08
> Furthermore, in this context, it would be interesting to know if a `$boost` without an explicit defined strength is equal to `$boost=1` or `$boost=2`?

Hey @devidw, I can't speak for the developers, and I can't find an answer in any of the documentation that I've read. But given my prior comment, knowing that `$boost=1` would not alter the ranking of a target, it would make sense to me that `$boost` (without an explicitly defined strength following it) by default would at least alter the ranking of the specified target by a maximum of 1 (i.e. `$boost=2`) to ensure the command carries out its specific intent.

Sorry if that explanation sounds complicated. If it makes it easier to understand, that Goggle you referenced was created by the Brave team, so I believe the `$boost` action (without an explicitly defined strength following it) was intended to equal `$boost=2`!

Hope this helps!

**Comment by devidw** [comment] 2022-08-17 18:29
Many thanks for the understandable explanation @Ompanime 🙌

**Comment by remusao** [comment] 2022-08-18 07:01
Hi @devidw and @dpbriggs,

Thanks for reaching out. As @Ompanime mentioned above in his excellent answer, `$boost` is a shortcut for `$boost=2 (in most Goggles, only one value of boosting is used, and being able to use `$boost` makes the instructions simpler).

Regarding the ranking of results with multiple values of `boost`, yes, a higher boost should make your result appear higher (i.e. `$boost=3` gives a result more importance than `$boost=2`).

I hope this helps,
I'm closing this since questions have been answered but feel free to reopen if anything is missing,

**Closed by remusao** 2022-08-18 07:01 UTC

**Comment by devidw** [comment] 2022-09-14 08:00
> knowing that $boost=1 would not alter the ranking of a target

Taking this into aspect, does this mean, that `$boost=1` and `$downrank=1` are equally, since in both cases a value of `1` does not change the ranking?

**Comment by remusao** [comment] 2022-09-15 10:26
Yes that's correct, it should be the same, but keep in mind that in practice, adding instructions with `boost=1` or `downrank=1` might still alter the search results you get since Brave Search will "extend" the set of results considered by taking into account your Goggle.

**Comment by devidw** [comment] 2022-09-15 16:45
It feels a little like quantum theory, that the existence of a non changing instruction could result in some changes because of its existence rather than what it is saying

I do not fully understand this tbh

But I guess this does not matter in practice that much

Because when we do not want to alter a result, we should not put it into the goggle instead of setting it with some crazy `=1` values

**Comment by remusao** [comment] 2022-09-15 19:18
Over time, it would be quite amazing to have a community forming around creating Goggles but also tooling. I could see how a linter tool could help creators use Goggle instructions well and avoid some of the possible traps you have already identified.

**Comment by devidw** [comment] 2022-09-18 13:01
Just made a first step into tooling by releasing the first beta version of [_Gearchy_](https://github.com/devidw/gearchy).

A web application that provides a graphical interactive goggle builder to create and edit goggles.

Under the hood, there is a tiny TS library [_Goggledy_](https://github.com/devidw/gearchy/tree/main/packages/goggledy#readme), which provides a basic API to parse and generate goggle code.

**Comment by remusao** [comment] 2022-09-18 15:24
This is great @devidw! I was wondering if it would be possible to have a way to access some of the features of this tool without having to provide a GitHub authorization token, though? It might make it more accessible to try out, and then the uploading to GitHub and such could be "unlocked" if a token is provided?

**Comment by devidw** [comment] 2022-09-18 16:08
> I was wondering if it would be possible to have a way to access some of the features of this tool without having to provide a GitHub authorization token, though?

Currently, Gearchy only integrates with GitHub as storage/hosting solution. 

But I could definitely imagine extending the application design to also support storing goggles locally with something like IndexedDB. 

Will track this in https://github.com/devidw/gearchy/issues/37 👍
